# compile :
# 	javac src/academic/model/*.java src/academic/driver/*.java src/academic/tabel/*.java -d bin

# test_01 :
# 	java -cp "bin;./libs/*" academic.driver.Driver1 tabel.Create

# test_02 :
# 	java -cp "bin;./libs/*" academic.tabel.Create 

# test_03 :
# 	java -cp "bin;./libs/*" insert 


compile :
	javac src/academic/model/*.java src/academic/driver/*.java -d bin

test_01 :
	cd bin && java academic.driver.Driver1